UCLStudievejlederApp/Controllers/FormularController.cs
using DatabaseAccess.FieldOfStudy;
using DatabaseAccess.FieldOfStudy.Models;
using DatabaseAccess.FormularDbAccess;
using DatabaseAccess.Institution;
using DatabaseAccess.Institution.Models;
using DatabaseAccess.Question;
using DatabaseAccess.QuestionAnswer;
using DatabaseAccess.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System.Security.Claims;
using UCLStudievejlederApp.Models.Formular;
using static DatabaseAccess.Question.AnswerOptionDb;
using static DatabaseAccess.Question.QuestionDb;

namespace UCLStudievejlederApp.Controllers
{
    [Authorize]
    public class FormularController : Controller
    {
        private readonly AnswerOptionDb _answerOptionDb;
        private readonly QuestionDb _questionDb;
        private readonly FormularDbAccess _formularDbAccess;
        private readonly UserDb _userDb;
        private readonly FieldOfStudyDb _fieldOfStudyDb;
        private readonly InstitutionDb _institutionDb;
        private readonly IMemoryCache _memoryCache;

        public FormularController(QuestionDb questionDb, FormularDbAccess formularDbAccess, UserDb userDb, AnswerOptionDb answerOptionDb, FieldOfStudyDb fieldOfStudyDb, InstitutionDb institutionDb, IMemoryCache memoryCache)
        {
            _questionDb = questionDb;
            _formularDbAccess = formularDbAccess;
            _userDb = userDb;
            _answerOptionDb = answerOptionDb;
            _fieldOfStudyDb = fieldOfStudyDb;
            _institutionDb = institutionDb;
            _memoryCache = memoryCache;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var userToken = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int userId = _userDb.GetUserId(userToken);

            FormularViewModel model = new FormularViewModel();
            //var cachedModel = _memoryCache.Get<FormularViewModel>("QuestionModel");

            //if (cachedModel != null)
            //    return View(cachedModel);

            model.Questions = _questionDb.GetAllQuestionsWithAnswers();
            string currentDate = DateTime.Now.ToString("MMMM yyyy");

            for (int i = -2; i <= 0; i++)
            {
                string dateString = DateTime.Now.AddMonths(i).ToString("MMMM yyyy");
                dateString = char.ToUpper(dateString[0]) + dateString.Substring(1).ToLower();
                model.Questions[0].AnswerOptions.Add(new AnswerOption { QuestionId = 1, AnswerOptionString = dateString, AnswerOptionId = i + 12, IsSelected = false });
            }

            //_memoryCache.Set("QuestionModel", model, TimeSpan.FromMinutes(5));

            SetInstitutionsAndFieldsOfStudy(userId, model);
            return View(model);
        }

        private void SetInstitutionsAndFieldsOfStudy(int userId, FormularViewModel model)
        {
            // To know which Fields of studies that are connected to a user, we retrieve them from the DB
            List<FieldOfStudyModel> usersFieldsOfStudy = _fieldOfStudyDb.GetFieldsOfStudyByUserId(userId);

            // For each AnswerOption in Question 7 (Question about Field Of Study) we check if 
            // any of the user's Fields of Studies is the same as the AnswerOption's AnswerOptionString
            // If found a match, then IsFavorite is set to true.
            foreach (AnswerOption option in model.Questions[6].AnswerOptions)
                if (usersFieldsOfStudy.Any(x => x.Name == option.AnswerOptionString))
                    option.IsFavorite = true;

            // Same procedure as finding connected FieldsOfStudies, we retrieve a list of Institutions connected to a user from DB
            List<InstitutionModel> usersInstitutions = _institutionDb.GetInstitutionsByUserId(userId);

            // Here we check if the List of Institutions that we just retrieved contains 1 element (And only 1!)
            if (usersInstitutions.Count == 1)
            {
                // Here we check if any of the AnswerOptions on Question 5 (Institution) is the same of any of
                // the Institutions that are connected to a user. If a match is found, then the option is selected.
                foreach (AnswerOption option in model.Questions[5].AnswerOptions)
                    if (usersInstitutions.Any(x => x.Name == option.AnswerOptionString))
                        model.Questions[5].SingleChosenOption = option.AnswerOptionId;
            }
        }

        [HttpPost] 
        public IActionResult PostFormular(FormularViewModel model)
        {
            // Get userId so we know who the formular was created by
            var userToken = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int userId = _userDb.GetUserId(userToken);
            int formularId = 0;

            foreach (var item in model.Questions)
            {
                if (item.SingleChosenOption > 0)
                {
                    AnswerOption option = item.AnswerOptions.Where(x => x.AnswerOptionId == item.SingleChosenOption).First();
                    option.IsSelected = true;
                }

                DateTime dateSubmitted;

                if (DateTime.TryParse(item.DropdownChosenOption, out dateSubmitted))
                {
                    dateSubmitted = DateTime.Parse(item.DropdownChosenOption);
                    formularId = _formularDbAccess.CreateNewFormular(userId, dateSubmitted);
                }
            }

            // Create answer for each answer from model where IsSelected = true
            foreach (Question questionAndOptions in model.Questions)
            {
                foreach (AnswerOption option in questionAndOptions.AnswerOptions)
                {
                    if (option.IsSelected)
                        _questionDb.CreateQuestionAnswer(option.QuestionId, option.AnswerOptionId, formularId);
                }
            }

            return RedirectToAction("FormularList");
        }

        public IActionResult FormularList()
        {
            var userToken = User.FindFirstValue(ClaimTypes.NameIdentifier);
            int userId = _userDb.GetUserId(userToken);

            MyFormularsModel model = new MyFormularsModel();
            List<FormularAnswers> answers = _answerOptionDb.GetFormularAnswers(userId);

            int currentFormularId = 0;
            for (int i = 0; i < answers.Count(); i++)
            {
                if (currentFormularId != answers[i].FormularId)
                {
                    currentFormularId = answers[i].FormularId;
                    model.Formulars.Add(new FormularListItemModel
                    {
                        Month = answers[i].DateSubmitted.ToString("MMMM yyyy"),
                        TypeOfEnquiry = answers[i].QuestionAnswer,
                        ConversationTime = answers[i + 1].QuestionAnswer,
                        Level = answers[i + 2].QuestionAnswer,
                        WhoWereGuided = answers[i + 3].QuestionAnswer,
                        ChoosePrimaryInstitution = answers[i + 4].QuestionAnswer,
                        ChooseAllFieldsOfStudies = answers[i + 5].QuestionAnswer,
                        SubjectCategory = answers[i + 6].QuestionAnswer,
                    });
                }
            }


            return View(model);
        }

        public IActionResult EditFormular()
        {
            return View();
        }
    }
}

UCLStudievejlederApp/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace UCLStudievejlederApp.Controllers
{
    public class NotificationController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

UCLStudievejlederApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DatabaseAccess.FieldOfStudy;
using DatabaseAccess.FieldOfStudy.Models;
using DatabaseAccess.Institution;
using DatabaseAccess.Institution.Models;
using DatabaseAccess.User;
using DatabaseAccess.User.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UCLStudievejlederApp.Data;
using UCLStudievejlederApp.Models.Generic;
using UCLStudievejlederApp.Models.User;
using static DatabaseAccess.FieldOfStudy.FieldOfStudyDb;
using static DatabaseAccess.User.UserDb;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace UCLStudievejlederApp.Controllers
{
    public class UserController : Controller
    {
        private SignInManager<ApplicationUser> _signManager;
        private UserManager<ApplicationUser> _userManager;
        private readonly UserDb _userDb;
        private readonly InstitutionDb _institutionDb;
        private readonly FieldOfStudyDb _fieldOfStudyDb;
        public UserController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signManager, FieldOfStudyDb fieldOfStudyDb, InstitutionDb institutionDb, UserDb userDb)
        {
            _userManager = userManager;
            _signManager = signManager;
            _userDb = userDb;
            _institutionDb = institutionDb;
            _fieldOfStudyDb = fieldOfStudyDb;
    }

        [HttpGet]
        public IActionResult CreateUser()
        {
            RegisterUserModel registerUserModel = new RegisterUserModel();

            foreach(InstitutionModel institution in _institutionDb.GetAllInstitutions())
                registerUserModel.AllInstitutions.Add(new UCLSelectModel { Id = institution.InstitutionId, Name = institution.Name });
            
            foreach (FieldOfStudyModel fieldOfStudy in _fieldOfStudyDb.GetAllFieldsOfStudy())
                registerUserModel.AllFieldsOfStudy.Add(new UCLSelectModel { Id = fieldOfStudy.FieldOfStudyId, Name = fieldOfStudy.Name });
           

            return View(registerUserModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser(RegisterUserModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email, FirstName = model.FirstName, LastName = model.LastName };
                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {

                    foreach (UCLSelectModel userInstitution in model.AllInstitutions)
                    {
                        if (userInstitution.IsSelected == true)
                            _institutionDb.LinkUserToInstitution(user.UserId, userInstitution.Id);
                    }

                    foreach (UCLSelectModel userFieldOfStudy in model.AllFieldsOfStudy)
                    {
                        if (userFieldOfStudy.IsSelected == true)
                            _fieldOfStudyDb.LinkUserToFieldOfStudy(user.UserId, userFieldOfStudy.Id);
                    }

                    model.SuccessMessage = $"Brugeren {model.FirstName} {model.LastName} blev oprettet.";

                    return View(model);
                }
            }

            return View(model);
        }

        public IActionResult EditUser()
        {
            List<UserMinimalModel> model = _userDb.GetMinimalUserList();

            return View(model);
        }

        [HttpGet]
        public IActionResult EditOneUser(int userId)
        {

            UserModel user = _userDb.GetUser(userId);
            user.FieldOfStudies = _fieldOfStudyDb.GetFieldsOfStudyByUserId(userId);
            user.Institutions = _institutionDb.GetInstitutionsByUserId(userId);

            RegisterUserModel model = new RegisterUserModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                UserId = user.UserId
            };

            foreach (InstitutionModel institution in _institutionDb.GetAllInstitutions())
                model.AllInstitutions.Add(new UCLSelectModel { Id = institution.InstitutionId, Name = institution.Name, IsSelected = user.Institutions.Any(x => x.InstitutionId == institution.InstitutionId) });

            foreach (FieldOfStudyModel fieldOfStudy in _fieldOfStudyDb.GetAllFieldsOfStudy())
                model.AllFieldsOfStudy.Add(new UCLSelectModel { Id = fieldOfStudy.FieldOfStudyId, Name = fieldOfStudy.Name, IsSelected = user.FieldOfStudies.Any(x => x.FieldOfStudyId == fieldOfStudy.FieldOfStudyId) });

            return View(model);
        }
        
        [HttpPost]
        public IActionResult EditOneUser(RegisterUserModel model)
        {
            UserModel user = _userDb.GetUser(model.UserId);
            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            _userDb.UpdateUser(user);

            return RedirectToAction("EditOneUser", new { userId = model.UserId });
        }

    }
}

UCLStudievejlederApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UCLStudievejlederApp</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/animation.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/register.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" asp-append-version="true">
    <link rel="stylesheet" href="~/UCLStudievejlederApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/edituser.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/inquiries.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/midler.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.2/css/buttons.dataTables.min.css" asp-append-version="true" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw=="crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/caf5d23898.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="">https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js></script>
    <script src="https://cdn.datatables.net/buttons/2.3.2/js/buttons.html5.min.js"></script>
</head>
<body>
@*    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UCLStudievejlederApp</a>
*@

    <div id="myNav" class="overlay">
        @*<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times</a>*@
        <div class="close-icon">
            <img class="closebtn" src="~/assets/icons/close.png" alt="Close" onclick="closeNav()" />
        </div>
        <h3>Indstillinger</h3>
        <div class="overlay-content">
            <a asp-controller="User" asp-action="CreateUser">Opret ny bruger</a>
            <a asp-controller="User" asp-action="EditUser">Administrér brugere</a>
            <a asp-controller="Formular" asp-action="EditFormular">Rediger formularindhold</a>
            <a asp-controller="Notification" asp-action="Index">Notifikationer</a>
        </div>
    </div><!-- OVERLAY -->

    <div class="sidebar-own">
        <a asp-controller="Formular" asp-action="Index" title="Registrér ny henvendelse"><img class="sidebar-icon border-own" src="~/assets/icons/pencil.png" /></a>
        <a asp-controller="Formular" asp-action="FormularList" title="Se dine henvendelser"><img class="sidebar-icon border-own" src="~/assets/icons/list.png" /></a>
        <a asp-controller="Statistics" asp-action="Index" title="Statistik"><img class="sidebar-icon border-own" src="~/assets/icons/statistics.png" /></a>
        <img title="Indstillinger" class="sidebar-icon" src="~/assets/icons/settings.png" onclick="openNav()" />
    </div><!-- SIDE BAR -->

    <div id="bg-blur">

    <header class="nav-header">
        <div class="logo"><a asp-controller="Formular" asp-action="Index"><img src="~/assets/images/logo-horisontal-mg.svg" alt="UCL Logo" /></a> </div>
        <div class="right-box">
            <a asp-controller="Formular" asp-action="Index"><img src="~/assets/icons/bell.png" alt="Notifications" title="Notifikationer"/></a>
            <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Formular", new { area = "" })">
                    <button type="submit" title="Log ud"><img src="~/assets/icons/right.png" alt="Log out" /></button>
            </form>
        </div>
    </header>
    <div class="master">
        <div class="main-container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    
    <footer class="footer">
        <div class="left-box">
            &copy; @DateTime.Now.Year - University College Lillebælt

        </div>
        <div class="footer-right-box">
                <p>Du er logget ind som @User.Identity?.Name</p>
            <img src="~/assets/images/happyman.png" />
        </div>
    </footer>
    </div><!-- BG BLUR -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>